##################################
# ISSUE TEMPLATE FOR BUG REPORTS #
##################################

name: Bug Report
description: Report a Bug occurring on one or more functions of the system.
title: "[BUG]: "
labels: ["Type: Bug Report", "Status: Opened"]
assignees:
  - Mestre-Tramador
body:
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Please explain concisely what was the behavior expected on your workflow.
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Please explain concisely what the is bug and the behavior you are facing.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please list all the steps to reproduce the bug on the environment.
      value: |
        1 -
        2 -
        3 -
        4 -
        5 -
        ...
    validations:
      required: true
  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution
      description: Inform a possible suggestion on how to solve the bug (not required).
    validations:
      required: false
  - type: markdown
    attributes:
      value: ---
  - type: input
    id: php_version
    attributes:
      label: PHP Version
      description: Version of PHP which the project was ran.
    validations:
      required: true
  - type: input
    id: sqlite_version
    attributes:
      label: SQLite Version
      description: Version of SQLite which the project was ran (specify only if the bug is about the database).
    validations:
      required: false
  - type: input
    id: project_version
    attributes:
      label: Project Version
      description: Used version of the project.
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: checkboxes
    id: no_duplicates
    attributes:
      label: Confirmation of No Duplicates
      description: Please make a Bug Report only if none equal was made, or else go check the existing one.
      options:
      - label: I have searched the existing issues and not found any equal.
        required: true
